<?php
use Drupal\Core\Template\Attribute;

/**
 *
 * @file
 * Primary module hooks for Hbk Cforge module.
 */
function hbk_cforge_mod_theme($existing, $type, $theme, $path) {
  $hooks['slider_block'] = [
    'preprocess functions' => [
      'template_preprocess_slider_block'
    ],
    'variables' => [
      'sliders' => [],
      'attributes' => NULL
    ]
  ];
  return $hooks;
}

function template_preprocess_slider_block(&$vars) {
}

