# Schema for the configuration files of the Hbk Cforge module.
hbk_cforge_mod.settings:
  type: config_object
  label: "Hbk Cforge settings"
  mapping:
    example:
      type: string
      label: "Example"
